apiVersion: apps/v1
kind: Deployment
metadata:
  name: intellweave-backend
spec:
  replicas: 2
  selector:
    matchLabels: { app: intellweave-backend }
  template:
    metadata:
      labels: { app: intellweave-backend }
    spec:
      containers:
        - name: backend
          image: ghcr.io/yourorg/intellweave-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom: { secretKeyRef: { name: db-secret, key: url } }
            - name: REDIS_URL
              value: redis://redis:6379/0
---
apiVersion: v1
kind: Service
metadata:
  name: intellweave-backend
spec:
  selector: { app: intellweave-backend }
  ports:
    - port: 80
      targetPort: 8000
